# Generated by Django 5.1 on 2024-09-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_member_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='record_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(max_length=10),
        ),
    ]
